language: node_js
node_js: node
services: mongodb
deploy:
  provider: heroku
  api_key:
    secure: ljGZiA1RdYnj30qS63OKXBw59ke4Ul+UUKTd1KsP0TVHQUN6BVebas1cbMUOG/j0gQtU3gjWoFUqs72swLnOpOdBniCywkw4py287+XoE6BeooCf2I+R7AUUcLYNx/vnmsH4AuOfHdUTaZYYbEfW0t+XXD1SwZV+LIwJKl+I9YvmaRTHEWXwNgfPNE6wtQtrFoAl7iAmU1Ar3ufyvmrkdUeafkPEawkUX9Rc7T45eu8JwC5pOurJ2T5qbGtmylDpHpn0LJBnTfgxaS9RyfSMV3powd7pLkHPNLPFECgjpeCJB9O4mB4xml1Hu+CQxOO0KVw7r1l6oOhtAw2R0wy/H2gqdlaHG2dUIsDsKOKhtCWPVUL9yxaW3ip3Sv0XxuOaDnssg5O/Y65MVF33/tWZ81RShb70JxLIIlDi9uJ2gEkTyIV4WJpWEjUwctKnS9y2U1+0nJV83tvrcIlfKp7rc7DjBJHnpCIakZCmN3qIa/gjqCYqs7cNqpJrr3ok7jK8F3eqgvL14qIhsAqQy8gr3Kqi70Sc7hH824Koeofnqdv+7sYSwvZiz6LpbRi9obnUYTyLsnoryXuDdrEAOuT0LKxuHaomq3s2UPujZLtz9erEXn6RrJSm1QVJX9KVlO7cn4Eyz/ZjF5MT9MvXM20Ue2VRXT70WOlngcrZAr62Viw=
  app: rocky-lowlands-17251
  on:
    repo: thinkful-ei24/gabriel-noteful-app-v3
